package:
  name: haskell
  version: 9.8
  target-architecture:
    - x86_64
    - aarch64
  epoch: 0
  description: The Haskell programming language
  url: https://www.haskell.org/
  # copyright:
  #   - license: GPL-2.0
  dependencies:
    runtime:
      # - gmp
      # - libffi

vars:
  ghcupVersion: 0.1.20.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      # apk add build-base ncurses texinfo curl
      - wolfi-base
      - build-base
      - ncurses
      # - ncurses-dev
      # - ncurses-static
      # - ncurses-terminfo
      # - ncurses-terminfo-base
      # - texinfo
      - curl

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: https://downloads.haskell.org/~ghcup/${{vars.ghcupVersion}}/x86_64-linux-ghcup-${{vars.ghcupVersion}}
          expected-sha256: 0634ab60c659ab14dab4f73d8ee9a7fb4c4e2e959406dc74ed967781df798a3d
          extract: false
          timeout: 30
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        # wget https://downloads.haskell.org/~ghcup/0.1.20.0/aarch64-linux-ghcup-0.1.20.0 && mv aarch64-linux-ghcup-0.1.20.0 /usr/bin/ghcup && chmod +x /usr/bin/ghcup
        with:
          uri: https://downloads.haskell.org/~ghcup/${{vars.ghcupVersion}}/aarch64-linux-ghcup-${{vars.ghcupVersion}}
          expected-sha256: 79cb967034ea20b495a7c4e99eefd2a3d4e41e964c69f50d5d626627995751e3
          extract: false
          timeout: 30
  - runs: |
      set -x

      # TODO: workaround
      ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfo.so.6
      find / -name 'libtinfo*'

      mv ${{build.arch}}-linux-ghcup-${{vars.ghcupVersion}} /usr/bin/ghcup
      chmod +x /usr/bin/ghcup
      ghcup --version
      ghcup install ghc 9.8 -f --isolate ${{targets.destdir}}/usr
      ghcup install cabal 3.10.2.1 -f --isolate ${{targets.destdir}}/usr/bin
