package:
  name: cabal
  version: 3.10.2.0
  epoch: 0
  description: The Haskell Cabal
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - x86_64
    - aarch64
  dependencies:
    runtime:
      - gmp

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: https://downloads.haskell.org/~cabal/Cabal-${{package.version}}/cabal-install-${{package.version}}-x86_64-linux-deb10.tar.xz
          expected-sha256: 5cd39a0aa6474592d7f2bfd696f08a0247546e17553ce774b320130aa1504953
          timeout: 30
          strip-components: 0
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          uri: https://downloads.haskell.org/~cabal/Cabal-${{package.version}}/cabal-install-${{package.version}}-aarch64-linux-deb10.tar.xz
          expected-sha256: 3c32810494afb950afa83e3b00890041bddf08e7a64a826c7433eea9aca2f626
          timeout: 30
          strip-components: 0
  - runs: |
      outdir=${{targets.destdir}}/usr/bin
      mkdir -p $outdir
      cp cabal $outdir
