name: Build and Push

on:
  release:
    types:
    - published
  push:
    branches:
    - '*'
    tags:
    - v*
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - target: basic
          imageSuffix: ""
        - target: python
          imageSuffix: "/python"

    steps:
    - uses: actions/checkout@v3
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/markdown-paper-setup${{ matrix.imageSuffix}}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
        flavor: |
          latest=${{ github.ref == 'refs/heads/master' }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: linux/amd64,linux/arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        target: ${{ matrix.target }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/markdown-paper-setup${{ matrix.imageSuffix}}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/markdown-paper-setup${{ matrix.imageSuffix}}:buildcache,mode=max
        secrets: |
          GIT_AUTH_TOKEN=${{ github.token }}
